version: '3'
services:
  codemap:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - 8123:8123
    env_file: ../.env
    depends_on:
      neo4j:
        condition: service_healthy

  neo4j:
    image: neo4j:5.1.0
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /data
    environment:
      - NEO4J_AUTH=neo4j/${DB_PASSWORD}
      - NEOMODEL_CYPHER_DEBUG=1
    healthcheck:
        test: wget http://localhost:7474 || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 3s
